global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.60.130.33:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]

  - job_name: 'kafka'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9308']