name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-application-jar
          path: build/libs/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: spring-application-jar
          path: build/libs

      # Docker 이미지 빌드
      - name: Build Docker image
        run: docker build . -t ${{ secrets.SEONGJIN_DOCKER_REPO }}:tag-${{ github.sha }}


      # Docker Hub에 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SEONGJIN_DOCKER_USERNAME }}
          password: ${{ secrets.SEONGJIN_DOCKER_PASSWORD }}

      # 이미지를 Docker 재태그 및 Hub에 푸시
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.SEONGJIN_DOCKER_REPO }}:tag-${{ github.sha }}

      - name: Checkout Kubernetes manifest repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SAAS_MANIFEST_REPO }}
          token: ${{ secrets.SAAS_MANIFEST_REPO_TOKEN }}
          ref: ${{ secrets.SEONGJIN_K8S_BRANCH }}

      - name: Update file
        run: |
          sed -i 's|^.*image:.*|          image: ${{ secrets.SEONGJIN_DOCKER_REPO }}:tag-${{ github.sha }}|' kube/springboot.yaml
          git config user.name ${{ secrets.SEONGJIN_USERNAME }}
          git config user.email ${{ secrets.SEONGJIN_EMAIL }}
          git add kube/springboot.yaml
          git commit -m "Update file via GitHub Actions"
          git push
