name: Java CI with Gradle

on:
  push:
    branches: [ "dev_hyeongwon" ]
  pull_request:
    branches: [ "dev_hyeongwon" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'

    - name: Build with Gradle Wrapper
      run: ./gradlew build
